<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>数据备份</title>
</head>
<body>
<div style="width:1000px;height:400px;margin:0 auto;display: table-cell;vertical-align: middle;color:blue;font-size:24px;">
	<center>数据已经被备份存放在项目的<span style="color:red">[根目录]</span>的地方</center>
</div>
</body>
</html>