<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>文章管理</title>
<script type="text/javascript" language="javascript" src="__PUBLIC__/js/jquery.min.js"></script>
<link href="__PUBLIC__/biaoqing/css/manhuaHtmlArea.1.0.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="__PUBLIC__/biaoqing/js/manhuaHtmlArea.1.0.js"></script>
<link type="text/css" rel="stylesheet" href="__PUBLIC__/css/pub.css" />
<link type="text/css" rel="stylesheet" href="__PUBLIC__/admin/css/wenguan.css" />
</head>
<body>
<div>
</div>

<table  width="1000px;" style=" border:2px solid #e0fcff;margin:0 auto;"cellspacing="0" cellpadding="0">
<?php $a = 0; if ($resu): echo "<pre>"; var_dump(); echo "</pre>";?>
<?php foreach ($resu  as $key => $val):  $hh ="c".$a ;?>
<script type="text/javascript">
	$(document).ready(function(){
		//alert("<?php echo $val['neirong']; ?>");
		$(".<?php echo $hh;?>").replaceContent("<?php echo $val['neirong']; ?>");
	});
</script>
	<tr style=" border-top:1px solid #e0fcff;">
		<td width="350px">&nbsp;</td>
		<td>
			<div style="text-align: center;font-size:24px;">
				<?php echo $val['biaoti'] ; ?>
			</div>
			<div style="text-align: right;font-size:14px;">
				<?php echo $val['leibie'] , $val['date'];?>
			</div>
		</td>
		<td width="350px">&nbsp;</td>	
	</tr>
	<tr>
		<td class="<?php echo $hh;?>" id="nei" colspan="3">&nbsp;</td>
	</tr>
<?php $a = $a+1; endforeach; ?>
<?php else: ?>
	<span>暂时没有内容！</span>
<?php endif; ?>	
</table>
</body>
</html>