<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<title>首页</title>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<script type="text/javascript" language="javascript" src="__PUBLIC__/js/jquery.min.js"></script>
<script type="text/javascript" language="javascript" src="__PUBLIC__/shou/topanv.js"></script>
<link rel="stylesheet" type="text/css"  href="__PUBLIC__/shou/topanv.v1.0.css" />
<script type="text/javascript">

</script>
</head>
<body>
<div id="topnavbar" style="display: block;">
	<div id="topnanv" style="width: 980px;">
		<div class="defu">
			<a href="#" target="_self">首页</a>
		</div>
		<div id="anvlfteb">
			<div selec="bbs" class="posbox"> <a href="#">新闻</a> <i></i></div>
			<div selec="news" class="posbox"><a href="#">信息</a> <i></i></div>
			<div selec="post" class="posbox"><a href="#">商家</a> <i></i></div>
			<div selec="youhui" class="posbox"><a href="#">社区</a> <i></i></div>
			<div selec="other" class="posbox"><a href="#">团购</a> <i></i></div>
			<div selec="store" class="posbox"><a href="#">房产</a> <i></i></div>
			<div id="seledbox" class="posiabox" style="display: none; left: 1px;"><div>
			</div></div>
		</div>
		<div style="display:none" id="topusers">登录中...</div>
		<div id="loginbtm">
			<a style="color:#FFF" target="_blank" href="#">免费发布信息</a> 
		</div>
	</div>
<img src="./Public/images/ico7.gif">抚州快讯
</div>
</body>
</html>